# Generated by Django 4.0.3 on 2023-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('user_id', models.TextField()),
                ('date', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
