# Generated by Django 4.0.3 on 2023-08-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pdfpath', models.CharField(max_length=300, null=True)),
                ('dflag', models.BooleanField(default=False)),
            ],
        ),
    ]
