# Generated by Django 4.0.3 on 2023-08-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfextract', '0002_url_comment_url_date_url_keyword_url_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='category',
            field=models.CharField(choices=[('선택', None), ('모욕죄', '개발'), ('명예훼손죄', '기획'), ('음란죄', '디자인')], default='선택', max_length=10),
        ),
    ]
