# Generated by Django 4.0.3 on 2023-08-17 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfextract', '0004_alter_url_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='currentuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='url',
            name='category',
            field=models.CharField(choices=[(None, None), ('모욕죄', '모욕죄'), ('명예훼손죄', '명예훼손죄'), ('음란죄', '음란죄')], default='선택', max_length=10),
        ),
    ]
