# Generated by Django 4.0.3 on 2023-08-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0002_survey_ans5'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
