# Generated by Django 4.2.4 on 2023-08-16 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('content', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached', models.FileField(null=True, upload_to='uploads/', verbose_name='첨부 파일')),
                ('crime', models.CharField(choices=[('INSULT', '모욕'), ('HONOR', '명예훼손'), ('INDECENT', '음란'), ('EX', '기타')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '증거',
                'db_table': 'evidence',
            },
        ),
    ]
