# Generated by Django 4.2.4 on 2023-08-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='attached',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='첨부 파일'),
        ),
    ]
