# Generated by Django 4.0.3 on 2023-08-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_userevidencelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='file_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='crime',
            field=models.CharField(max_length=200),
        ),
    ]
